# Permalinks
permalink:        pretty

# Setup
url:              http://vkblog.github.io

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            Woman. Legend.Blog

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  This blog has it all: Russian despair, American cynicism, and Nutella. Welcome!

# The tags listed as entries in the sidebar
# sidebar_tags:     [jekyll, hyde]

# Fallback image and color if not overwritten for tag or post
image:            https://raw.githubusercontent.com/vkblog/vkblog.github.io/master/public/img/thinker.jpg
color:            '#A85641'

author:
  name:           'Vicki Boykis'
  twitter:        vboykis
  github:         veekaybee
  photo:          https://raw.githubusercontent.com/vkblog/vkblog.github.io/master/public/img/profile.jpeg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  # about:          |
  #   Hi, I'm Florian or [`@qwtel`](https://www.twitter.com/qwtel), which isn't an acronym,
  #   I just [wanted a short username](http://qwtel.com/how-to-find-a-short-username) and that one happened to be available.

  #   Read my thoughts on [#software](http://qwtel.com/tag/software) and [#cryptoeconomics](http://qwtel.com/tag/cryptoeconomics).
